-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT A.CAR_ID as CAR_ID, A.CAR_TYPE as CAR_TYPE,
       FLOOR(A.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100) as FEE
FROM CAR_RENTAL_COMPANY_CAR as A
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
  AND A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
      AND END_DATE >= '2022-11-01'
)
  AND C.DURATION_TYPE = '30일 이상'
  AND FLOOR(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC